version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  # apt_packages:
  #   - graphviz
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
    install:
      - uv pip install .[docs]

    build:
      html:
        - NO_COLOR=1 uv run mkdocs build --site-dir $READTHEDOCS_OUTPUT/html

mkdocs:
  configuration: mkdocs.yml
  
formats:
  - pdf
